# Generated by Django 5.1.3 on 2024-11-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortner', '0002_url_expiry_date_url_password_url_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='uuid',
            field=models.CharField(default='5cc8f671-9d7e-49ca-bf8b-2c50f2a4cd3e', max_length=36, unique=True),
        ),
    ]
